version: "3.7"

services:
  terraform:
    image: hashicorp/terraform:1.7.5
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform/environments/dev
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=ap-northeast-1